### ISSUE TITLE
WebM and stability issues

### ISSUE THREAD

**Issue by Chessax** [Marginal/QLVideo#41]
I'm having various issues which I believe are related to certain WebM files.

Running:
OS X 10.9.5 (I know I'm running an almost legacy system, so don't really expect a fix, but one can always hope.)
QLVideo 1.88

I also tried to reset Finder preferences to default, with no luck.

Showing info in Finder also caused a corrupt "after image" graphics glitch where the tags text area was supposed to be on all WebM files, but instead showing seemingly random screen areas to appear in its place. An additional Finder restart solved this, so I'm not sure if it is related (it most likely is since this is the first time seeing it) or exactly what caused it.

I'm also getting a lot of the following in logs, but doesn't seem to be detrimental to use:
```
Finder[6378]: +[CATransaction synchronize] called within transaction
```

List view in Finder is not working either and causes the below error in logs (most likely when seeing some kind of non-working WebM). I.e. the list view freezes and current graphics on screen is "echoed" into the list view (see _list_view.png_) or simply large areas of empty space where files should be listed. After this QuickLook preview sometimes refuses to work at all (e.g. even raw text files or folders stop working). It either shows up blank, as saying that nothing is selected or QuickLook preview not showing up at all when triggered. I have not yet been able to identify exactly when list view freezes, however the following error shows up in icon view as well but seemingly less frequent:

```
Finder[6378]: -[__NSCFString timeIntervalSinceReferenceDate]: unrecognized selector sent to instance 0x608004c405a0
Finder[6378]: -[__NSCFString timeIntervalSinceReferenceDate]: unrecognized selector sent to instance 0x608004c405a0
Finder[6378]: (
	0   CoreFoundation                      0x00007fff8ef3825c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff93620e75 objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8ef3b12d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff8ee96272 ___forwarding___ + 1010
	4   CoreFoundation                      0x00007fff8ee95df8 _CF_forwarding_prep_0 + 120
	5   DesktopServicesPriv                 0x00007fff91d2ccfc _ZNK13TMDItemRecord16GetTimeAttributeEPK10__CFStringb + 166
	6   DesktopServicesPriv                 0x00007fff91c6a37a _ZNK7TFSInfo15GetCreationDateEv + 72
	7   DesktopServicesPriv                 0x00007fff91c83073 _ZNK5TNode18LowLevelIsLockFileEv + 237
	8   DesktopServicesPriv                 0x00007fff91c795b8 _ZNK5TNode6NodeIsERy + 880
	9   DesktopServicesPriv                 0x00007fff91c791ed NodeIs + 93
	10  Finder                              0x000000010272359b Finder + 95643
	11  Finder                              0x000000010275aa22 Finder + 322082
	12  Finder                              0x000000010275e8d5 Finder + 338133
	13  Finder                              0x00000001027f63c2 Finder + 959426
	14  Finder                              0x00000001027f622a Finder + 959018
	15  Finder                              0x00000001027f6044 Finder + 958532
	16  Finder                              0x00000001027f4d77 Finder + 953719
	17  AppKit                              0x00007fff8c378944 -[NSTableView(NSTableViewViewBased) makeViewForTableColumn:row:] + 77
	18  AppKit                              0x00007fff8c377c77 -[NSTableRowData _addViewToRowView:atColumn:row:] + 305
	19  AppKit                              0x00007fff8c3779aa -[NSTableRowData _addViewsToRowView:atRow:] + 191
	20  AppKit                              0x00007fff8c374a9e -[NSTableRowData _addRowViewForVisibleRow:withPriorView:] + 421
	21  AppKit                              0x00007fff8c37481c -[NSTableRowData _addRowViewForVisibleRow:withPriorRowIndex:inDictionary:withRowAnimation:] + 278
	22  AppKit                              0x00007fff8c3738e6 -[NSTableRowData _unsafeUpdateVisibleRowEntries] + 1640
	23  AppKit                              0x00007fff8c37317c -[NSTableRowData updateVisibleRowViews] + 230
	24  AppKit                              0x00007fff8c41472d -[NSTableView viewWillDraw] + 165
	25  AppKit                              0x00007fff8c414673 -[NSOutlineView viewWillDraw] + 172
	26  Finder                              0x00000001027f1230 Finder + 938544
	27  AppKit                              0x00007fff8c41dcf1 -[NSView(NSInternal) _sendViewWillDrawAndRecurse:] + 332
	28  AppKit                              0x00007fff8c41d98f -[NSView(NSLayerKitGlue) _layoutSublayersOfLayer:] + 147
	29  QuartzCore                          0x00007fff8f4fae51 -[CALayer layoutSublayers] + 214
	30  AppKit                              0x00007fff8c41d8eb _NSBackingLayerLayoutSublayers + 160
	31  QuartzCore                          0x00007fff8f4faa25 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 363
	32  AppKit                              0x00007fff8c4a3e7e -[NSView _pullInTilesByDrawingAndAddingSubviews] + 83
	33  AppKit                              0x00007fff8c4a3e12 -[NSView _pullInExtraTilesForOverdraw] + 87
	34  AppKit                              0x00007fff8c4a3d7e -[NSView _doIdlePrefetch] + 59
	35  AppKit                              0x00007fff8c4a188a __CreateIdleRunLoopObserverWithHandler_block_invoke + 237
	36  CoreFoundation                      0x00007fff8ee68d67 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	37  CoreFoundation                      0x00007fff8ee68cd7 __CFRunLoopDoObservers + 391
	38  CoreFoundation                      0x00007fff8ee5a493 __CFRunLoopRun + 995
	39  CoreFoundation                      0x00007fff8ee59e75 CFRunLoopRunSpecific + 309
	40  HIToolbox                           0x00007fff91494a0d RunCurrentEventLoopInMode + 226
	41  HIToolbox                           0x00007fff914947b7 ReceiveNextEventCommon + 479
	42  HIToolbox                           0x00007fff914945bc _BlockUntilNextEventMatchingListInModeWithFilter + 65
	43  AppKit                              0x00007fff8c2be24e _DPSNextEvent + 1434
	44  AppKit                              0x00007fff8c2bd89b -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
	45  AppKit                              0x00007fff8c2b199c -[NSApplication run] + 553
	46  AppKit                              0x00007fff8c29c783 NSApplicationMain + 940
	47  Finder                              0x0000000102712730 Finder + 26416
	48  libdyld.dylib                       0x00007fff8ac305fd start + 1
	49  ???                                 0x0000000000000001 0x0 + 1
)
```

Eventually QuickLook itself got fed up with QLVideo, especially when QLVideo crashes, e.g.:
```
com.apple.quicklook.satellite[7376]: Video.qlgenerator crashed!
com.apple.launchd[1]: (com.apple.quicklook.satellite.EB0D6580-603E-4B43-A701-D0EE72633885[7376]) Exited with code: 1
com.apple.launchd[1]: (com.apple.quicklook.satellite.EB0D6580-603E-4B43-A701-D0EE72633885) Throttling respawn: Will start in 5 seconds
quicklookd[]: [QL] Client is talking to a session twice at the same time: for <QLPreviewRequest []> and <QLPreviewRequest []>
QuickLookUIHelper[]: [QL] Getting a (not created) callback on client but there is no client
QuickLookUIHelper[]: [QL] Too many problems with <QLGenerator /Library/QuickLook/Video.qlgenerator>. Disabling it
```

```
$ qlmanage -m
server: living for 40s (3 requests handled) - instant off: yes - arch: X86_64 - user id: 501
memory used: 1 MB (1082624 bytes) - used descriptors: 19/256
last burst: during 0.454s - 3 requests - 0.115s idle
plugins:
  org.openxmlformats.presentationml.slideshow -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.adobe.pdf -> /System/Library/QuickLook/PDF.qlgenerator (622.7)
  com.apple.localized-pdf-bundle -> /System/Library/QuickLook/LocPDF.qlgenerator (622.7)
  com.apple.iwork.keynote.key -> /Library/QuickLook/iWork.qlgenerator (86)
  com.apple.application -> /System/Library/QuickLook/StandardBundles.qlgenerator (622.7)
  com.apple.ical.bookmark -> /System/Library/QuickLook/iCal.qlgenerator (622.7)
  com.microsoft.word.doc -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.microsoft.powerpoint.pot -> /System/Library/QuickLook/Office.qlgenerator (32)
  org.openxmlformats.wordprocessingml.template.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.iwork.keynote.sffkey -> /Library/QuickLook/iWork.qlgenerator (86)
  com.apple.ichat.ichat -> /System/Library/QuickLook/iChat.qlgenerator (4226)
  com.apple.notes.externalrecord -> /System/Library/QuickLook/Notes.qlgenerator (284)
  com.microsoft.word.dot -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.iwork.keynote.sffkth -> /Library/QuickLook/iWork.qlgenerator (86)
  org.openxmlformats.presentationml.template.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.keynote.key -> /Library/QuickLook/iWork.qlgenerator (86)
  com.apple.mail.email -> /System/Library/QuickLook/Mail.qlgenerator (1878.6)
  com.apple.iwork.pages.sfftemplate -> /Library/QuickLook/iWork.qlgenerator (86)
  com.parallels.vm.vmpackage -> /Applications/Parallels Desktop.app/Contents/Library/QuickLook/ParallelsQL.qlgenerator (10.0.0)
  public.movie -> /Library/QuickLook/Video.qlgenerator (1.8.8 - loaded)
  com.apple.iwork.keynote.kth -> /Library/QuickLook/iWork.qlgenerator (86)
  com.apple.iwork.numbers.sffnumbers -> /Library/QuickLook/iWork.qlgenerator (86)
  com.apple.package -> /System/Library/QuickLook/Package.qlgenerator (622.7)
  org.openxmlformats.wordprocessingml.document.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.iwork.pages.sffpages -> /Library/QuickLook/iWork.qlgenerator (86)
  com.apple.ical.ics -> /System/Library/QuickLook/iCal.qlgenerator (622.7)
  org.oasis-open.opendocument.text -> /System/Library/QuickLook/Text.qlgenerator (622.7)
  org.openxmlformats.wordprocessingml.template -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.ical.ics.event -> /System/Library/QuickLook/iCal.qlgenerator (622.7)
  com.microsoft.excel.xlt -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.iwork.numbers.sfftemplate -> /Library/QuickLook/iWork.qlgenerator (86)
  com.apple.iwork.keynote.key-tef -> /Library/QuickLook/iWork.qlgenerator (86)
  com.apple.ibooksauthor.book -> /Library/QuickLook/iBooksAuthor.qlgenerator (1.0)
  com.apple.internet-location -> /System/Library/QuickLook/Clippings.qlgenerator (622.7)
  com.rsa.pkcs-12 -> /System/Library/QuickLook/Security.qlgenerator (55047)
  org.openxmlformats.presentationml.slideshow.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.microsoft.word.stationery -> /System/Library/QuickLook/Office.qlgenerator (32)
  public.x509-printable-encoded-archive -> /System/Library/QuickLook/Security.qlgenerator (55047)
  public.xml -> /System/Library/QuickLook/Text.qlgenerator (622.7)
  org.openxmlformats.wordprocessingml.document -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.rtfd -> /System/Library/QuickLook/Text.qlgenerator (622.7)
  org.bittorrent.bittorrentpartfile -> /Applications/uTorrent.app/Contents/Library/QuickLook/QuickLookPlugin.qlgenerator (1.0)
  com.apple.systempreference.prefpane -> /System/Library/QuickLook/StandardBundles.qlgenerator (622.7)
  org.openxmlformats.spreadsheetml.template -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.keychain -> /System/Library/QuickLook/Security.qlgenerator (55047)
  public.font -> /System/Library/QuickLook/Font.qlgenerator (622.7)
  public.x509-certificate -> /System/Library/QuickLook/Security.qlgenerator (55047)
  com.apple.iwork.pages.template -> /Library/QuickLook/iWork.qlgenerator (86)
  com.adobe.illustrator.ai-image -> /System/Library/QuickLook/EPS.qlgenerator (622.7)
  public.vcard -> /System/Library/QuickLook/Contact.qlgenerator (622.7)
  com.apple.finder.textclipping -> /System/Library/QuickLook/Clippings.qlgenerator (622.7)
  org.openxmlformats.presentationml.template -> /System/Library/QuickLook/Office.qlgenerator (32)
  org.videolan.webm -> /Library/QuickLook/Video.qlgenerator (1.8.8 - loaded)
  org.openxmlformats.spreadsheetml.template.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.iwork.numbers.numbers -> /Library/QuickLook/iWork.qlgenerator (86)
  com.apple.iwork.pages.pages -> /Library/QuickLook/iWork.qlgenerator (86)
  com.apple.ichat.transcript -> /System/Library/QuickLook/iChat.qlgenerator (4226)
  com.apple.mail.emlx -> /System/Library/QuickLook/Mail.qlgenerator (1878.6)
  com.apple.iconset -> /System/Library/QuickLook/Icon.qlgenerator (622.7)
  com.apple.addressbook.group -> /System/Library/QuickLook/Contact.qlgenerator (622.7)
  com.apple.property-list -> /System/Library/QuickLook/Text.qlgenerator (622.7)
  com.apple.addressbook.person -> /System/Library/QuickLook/Contact.qlgenerator (622.7)
  com.apple.safari.history -> /System/Library/QuickLook/Bookmark.qlgenerator (622.7)
  public.html -> /System/Library/QuickLook/Web.qlgenerator (622.7)
  com.apple.iwork.numbers.template -> /Library/QuickLook/iWork.qlgenerator (86)
  com.microsoft.powerpoint.pps -> /System/Library/QuickLook/Office.qlgenerator (32)
  public.plain-text -> /System/Library/QuickLook/Text.qlgenerator (622.7)
  public.webp -> /Library/QuickLook/WebpQuickLook.qlgenerator (1.0)
  com.apple.safari.bookmark -> /System/Library/QuickLook/Bookmark.qlgenerator (622.7)
  public.audio -> /System/Library/QuickLook/Audio.qlgenerator (622.7)
  org.khronos.collada.digital-asset-exchange -> /System/Library/QuickLook/SceneKit.qlgenerator (197.5)
  com.apple.pict -> /System/Library/QuickLook/Clippings.qlgenerator (622.7)
  public.xhtml -> /System/Library/QuickLook/Web.qlgenerator (622.7)
  com.mathworks.simulink-model-slx -> /Applications/MATLAB_R2014a.app/Contents/Library/QuickLook/quickLookSLX.qlgenerator (8.3.0)
  org.openxmlformats.presentationml.presentation.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.finder.pictclipping -> /System/Library/QuickLook/Clippings.qlgenerator (622.7)
  com.apple.ical.bookmark.todo -> /System/Library/QuickLook/iCal.qlgenerator (622.7)
  com.apple.iwork.numbers.numbers-tef -> /Library/QuickLook/iWork.qlgenerator (86)
  com.apple.webarchive -> /System/Library/QuickLook/Web.qlgenerator (622.7)
  org.openxmlformats.presentationml.presentation -> /System/Library/QuickLook/Office.qlgenerator (32)
  public.svg-image -> /System/Library/QuickLook/Web.qlgenerator (622.7)
  public.image -> /System/Library/QuickLook/Image.qlgenerator (622.7)
  org.openxmlformats.spreadsheetml.sheet -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.microsoft.excel.xls -> /System/Library/QuickLook/Office.qlgenerator (32)
  org.openxmlformats.spreadsheetml.sheet.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  public.rtf -> /System/Library/QuickLook/Text.qlgenerator (622.7)
  net.daringfireball.markdown -> /Library/QuickLook/QLMarkdown.qlgenerator (1.0)
  org.bittorrent.torrent -> /Applications/uTorrent.app/Contents/Library/QuickLook/QuickLookPlugin.qlgenerator (1.0)
  org.bittorrent.utorrentpartfile -> /Applications/uTorrent.app/Contents/Library/QuickLook/QuickLookPlugin.qlgenerator (1.0)
  com.apple.iwork.pages.pages-tef -> /Library/QuickLook/iWork.qlgenerator (86)
  com.microsoft.powerpoint.ppt -> /System/Library/QuickLook/Office.qlgenerator (32)
  public.comma-separated-values-text -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.ical.ics.todo -> /System/Library/QuickLook/iCal.qlgenerator (622.7)
  com.adobe.encapsulated-postscript -> /System/Library/QuickLook/EPS.qlgenerator (622.7)
  com.microsoft.advanced-systems-format -> /Library/QuickLook/Video.qlgenerator (1.8.8 - loaded)
  com.mathworks.matlab-app-install -> /Applications/MATLAB_R2014a.app/Contents/Library/QuickLook/quickLookSLX.qlgenerator (8.3.0)
```

Attached in the zip file are random WebM files that do not appear to work.

![list_view](https://user-images.githubusercontent.com/21975105/27050848-40be8656-4fb4-11e7-9e5a-5a4cd10d8ac1.png)
[A.zip](https://github.com/Marginal/QLVideo/files/1069267/A.zip)

**Comment by Marginal** [comment]
Thanks for the sample files. Fixed in [Release 1.89](https://github.com/Marginal/QLVideo/releases/latest).

**Comment by Chessax** [comment]
Can confirm that the sample files now "work", thanks! (i.e. they all get thumbs and QL previews)

However list view is still not working, but I've narrowed it down to having to do with searching in Finder. E.g. searching for sample file "etJ87sW.webm" (only result) works in both icon and list view, but "3a24dd43594fb400e8ed7f8451836b9c.webm" (only result) does not:

List view (no results shown):
```
2017-06-16 21:16:54,631 Finder[7815]: -[__NSCFString timeIntervalSinceReferenceDate]: unrecognized selector sent to instance 0x608000e540d0
2017-06-16 21:16:54,633 Finder[7815]: -[__NSCFString timeIntervalSinceReferenceDate]: unrecognized selector sent to instance 0x608000e540d0
2017-06-16 21:16:54,633 Finder[7815]: (
	0   CoreFoundation                      0x00007fff8ef3825c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff93620e75 objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8ef3b12d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff8ee96272 ___forwarding___ + 1010
	4   CoreFoundation                      0x00007fff8ee95df8 _CF_forwarding_prep_0 + 120
	5   DesktopServicesPriv                 0x00007fff91d2ccfc _ZNK13TMDItemRecord16GetTimeAttributeEPK10__CFStringb + 166
	6   DesktopServicesPriv                 0x00007fff91c6a37a _ZNK7TFSInfo15GetCreationDateEv + 72
	7   DesktopServicesPriv                 0x00007fff91c915ca _ZNK5TNode11GetPropertyEjR18TPropertyReferencej + 990
	8   DesktopServicesPriv                 0x00007fff91ca3462 _NodeCopyValuesForSortRecordArray + 1172
	9   Finder                              0x0000000100e3e64d Finder + 333389
	10  Finder                              0x0000000100e9bece Finder + 716494
	11  Finder                              0x0000000100e9bdae Finder + 716206
	12  Finder                              0x0000000100ed3c34 Finder + 945204
	13  Finder                              0x0000000100e38f53 Finder + 311123
	14  Finder                              0x0000000100e16edc Finder + 171740
	15  Finder                              0x0000000100e16dc7 Finder + 171463
	16  Finder                              0x0000000100e0fd32 Finder + 142642
	17  libdispatch.dylib                   0x00007fff92b2f1bb _dispatch_call_block_and_release + 12
	18  libdispatch.dylib                   0x00007fff92b2c28d _dispatch_client_callout + 8
	19  libdispatch.dylib                   0x00007fff92b2e673 _dispatch_queue_drain + 451
	20  libdispatch.dylib                   0x00007fff92b2f9c1 _dispatch_queue_invoke + 110
	21  libdispatch.dylib                   0x00007fff92b2df87 _dispatch_root_queue_drain + 75
	22  libdispatch.dylib                   0x00007fff92b2f177 _dispatch_worker_thread2 + 40
	23  libsystem_pthread.dylib             0x00007fff91bf5ef8 _pthread_wqthread + 314
	24  libsystem_pthread.dylib             0x00007fff91bf8fb9 start_wqthread + 13
)
```

Icon view (works once, but then **all** subsequent searches fail):
```
2017-06-16 21:19:25,853 Finder[7815]: -[__NSCFString timeIntervalSinceReferenceDate]: unrecognized selector sent to instance 0x610000e423a0
2017-06-16 21:19:25,854 Finder[7815]: -[__NSCFString timeIntervalSinceReferenceDate]: unrecognized selector sent to instance 0x610000e423a0
2017-06-16 21:19:25,856 Finder[7815]: (
	0   CoreFoundation                      0x00007fff8ef3825c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff93620e75 objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8ef3b12d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff8ee96272 ___forwarding___ + 1010
	4   CoreFoundation                      0x00007fff8ee95df8 _CF_forwarding_prep_0 + 120
	5   DesktopServicesPriv                 0x00007fff91d2ccfc _ZNK13TMDItemRecord16GetTimeAttributeEPK10__CFStringb + 166
	6   DesktopServicesPriv                 0x00007fff91c6a37a _ZNK7TFSInfo15GetCreationDateEv + 72
	7   DesktopServicesPriv                 0x00007fff91c69d0e _ZN7TFSInfo15FetchPropertiesEv + 2372
	8   DesktopServicesPriv                 0x00007fff91c6a266 _ZNK7TFSInfo20InitializeIfQueryHitEv + 198
	9   DesktopServicesPriv                 0x00007fff91c6a151 _ZNK7TFSInfo7GetNameEv + 15
	10  DesktopServicesPriv                 0x00007fff91c717bf _ZNK5TNode16GetCanonicalNameER8TUString + 65
	11  DesktopServicesPriv                 0x00007fff91c71446 _ZNK5TNode15AsFullPOSIXPathER8TUString + 604
	12  DesktopServicesPriv                 0x00007fff91ca4203 _ZN12TProgressMap11GetProgressERK8TNodePtrR13TProgressInfo + 79
	13  DesktopServicesPriv                 0x00007fff91ca3a01 _ZNK5TNode18CopyInlineProgressEv + 59
	14  DesktopServicesPriv                 0x00007fff91c9149d _ZNK5TNode11GetPropertyEjR18TPropertyReferencej + 689
	15  DesktopServicesPriv                 0x00007fff91c90f1d _ZNK5TNode11GetPropertyEjR18TPropertyReferenceRKP17OpaqueNodeRequestj + 69
	16  DesktopServicesPriv                 0x00007fff91ca3963 NodeCopyPropertyAsCFDictionary + 127
	17  Finder                              0x0000000100e3edb1 Finder + 335281
	18  Finder                              0x0000000100ea08cb Finder + 735435
	19  Finder                              0x0000000100ea07e2 Finder + 735202
	20  ImageKit                            0x00007fff8f3802a6 -[IKImageCell validateDatasource] + 272
	21  ImageKit                            0x00007fff8f38003d -[IKImageCell imageIsImported] + 54
	22  ImageKit                            0x00007fff8f3f6f7d -[IKFinderCell imageFrameForImageContainerFrame:useAspectRatio:] + 178
	23  ImageKit                            0x00007fff8f3f71e8 -[IKFinderCell imageFrameForImageContainerFrame:] + 75
	24  ImageKit                            0x00007fff8f2a8a28 -[IKImageBrowserCell _computeImageFrame] + 112
	25  ImageKit                            0x00007fff8f2a8f9f -[IKImageBrowserCell imageFrame] + 46
	26  ImageKit                            0x00007fff8f2a8ffa -[IKImageBrowserCell imageBorderFrame] + 41
	27  ImageKit                            0x00007fff8f3968d3 -[IKIconCell selectionFrame] + 43
	28  ImageKit                            0x00007fff8f397bf8 -[IKIconCell titleFrameForCellFrame:] + 47
	29  ImageKit                            0x00007fff8f397ce8 -[IKIconCell titleFrame] + 94
	30  ImageKit                            0x00007fff8f2ae439 -[IKImageBrowserCell titleIsTruncated] + 54
	31  ImageKit                            0x00007fff8f398d7a -[IKIconCell titleIsTruncated] + 39
	32  ImageKit                            0x00007fff8f2ae4db -[IKImageBrowserCell installToolTips] + 104
	33  ImageKit                            0x00007fff8f3416be -[IKImageBrowserView(IKToolTips) installToolTips] + 153
	34  ImageKit                            0x00007fff8f2d9e72 -[IKImageBrowserView(ImageBrowserEvents) updateTrackingAreas] + 147
	35  Finder                              0x0000000100e6cff8 Finder + 524280
	36  Finder                              0x0000000100e7108c Finder + 540812
	37  Finder                              0x0000000100e81bf2 Finder + 609266
	38  Finder                              0x0000000100e818a3 Finder + 608419
	39  Finder                              0x0000000100e39cf8 Finder + 314616
	40  Finder                              0x0000000100e81624 Finder + 607780
	41  Finder                              0x0000000100e814ce Finder + 607438
	42  Finder                              0x0000000100e39b79 Finder + 314233
	43  Finder                              0x0000000100e399e9 Finder + 313833
	44  Finder                              0x0000000100e13c85 Finder + 158853
	45  Finder                              0x0000000100e13c4c Finder + 158796
	46  libdispatch.dylib                   0x00007fff92b2f1bb _dispatch_call_block_and_release + 12
	47  libdispatch.dylib                   0x00007fff92b2c28d _dispatch_client_callout + 8
	48  libdispatch.dylib                   0x00007fff92b33ef0 _dispatch_main_queue_callback_4CF + 333
	49  CoreFoundation                      0x00007fff8ee9f4f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	50  CoreFoundation                      0x00007fff8ee5a714 __CFRunLoopRun + 1636
	51  CoreFoundation                      0x00007fff8ee59e75 CFRunLoopRunSpecific + 309
	52  HIToolbox                           0x00007fff91494a0d RunCurrentEventLoopInMode + 226
	53  HIToolbox                           0x00007fff914947b7 ReceiveNextEventCommon + 479
	54  HIToolbox                           0x00007fff914945bc _BlockUntilNextEventMatchingListInModeWithFilter + 65
	55  AppKit                              0x00007fff8c2be24e _DPSNextEvent + 1434
	56  AppKit                              0x00007fff8c2bd89b -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
	57  AppKit                              0x00007fff8c2b199c -[NSApplication run] + 553
	58  AppKit                              0x00007fff8c29c783 NSApplicationMain + 940
	59  Finder                              0x0000000100df3730 Finder + 26416
	60  libdyld.dylib                       0x00007fff8ac305fd start + 1
	61  ???                                 0x0000000000000001 0x0 + 1
)
2017-06-16 21:19:25,871 Finder[7815]: -[__NSCFString timeIntervalSinceReferenceDate]: unrecognized selector sent to instance 0x610000e423a0
```
